# Use '§' or '&' to change the color of the message.

messages:
  # Chat filter bypass permission: chatfilter.bypass
  warning-message: '§c§lThere is a forbidden word in your message. §r§7You can get a mute for excessive matting!'
  enable-warning-message: false

  block-message: "§c§lYour message has been blocked. §r§7You can get a mute for excessive matting!"
  enable-block-message: true

chatfilter:
  # Example: Hello will be replaced with ****
  replace-symbol: '*'
  # Available: block - message blocking, replace - replacing the message with stars.
  filter-type: "replace"

# You can continue this list as long as you want just copy my examples above
muted-words:
  - 'nigger'
  - 'beaner'
  - 'n1gger'
  - 'nibba'
  - 'fuck'
  - 'bitch'
  - 'cunt'
  - 'slut'
  - 'whore'
  - 'ass'
  - 'asshole'
