chatfilter:
  bypass-permission: 'chatfilter.bypass'
  warning-message: '&d&lYOUR SERVER HERE &8» &bWe''ve noticed you''re using &6Profane Language &ba lot. Please keep it to a minimum.'


#Example: Hello will be replaced with ****
replace-symbol: '*'


# You can continue this list as long as you want just copy my examples above
# NOTE: I do find these words HIGHLY OFFENSIVE and Recommend you keep them
muted-words:
- 'nigger'
- 'beaner'
- 'n1gger'
- 'nibba'
- 'fuck'
- 'bitch'
- 'cunt'
- 'slut'
- 'whore'
- 'ass'
- 'asshole'
